# Generated by Django 6.1.1 on 2026-09-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_customer_invoice_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Company Pvt. Ltd.', max_length=200)),
                ('pan_number', models.CharField(default='123456789', max_length=20, verbose_name='Seller PAN/VAT No.')),
                ('address', models.CharField(default='Kathmandu, Nepal', max_length=255)),
                ('phone', models.CharField(blank=True, default='+977-1-4000000', max_length=50)),
                ('email', models.EmailField(blank=True, default='info@mycompany.com.np', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Standard Nepal IRD Tax Invoice', max_length=100)),
                ('page_size', models.CharField(choices=[('A4_PORTRAIT', 'A4 Portrait (210mm x 297mm)'), ('A4_LANDSCAPE', 'A4 Landscape (297mm x 210mm)'), ('A5_PORTRAIT', 'A5 Portrait (148mm x 210mm)'), ('A5_LANDSCAPE', 'A5 Landscape (210mm x 148mm)')], default='A4_PORTRAIT', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('show_hs_code', models.BooleanField(default=True)),
                ('show_nepali_header', models.BooleanField(default=True, verbose_name="Show 'कर बीजक'")),
                ('header_subtitle', models.CharField(default='Schedule 5 (Rule 17), VAT Rules 2053', max_length=150)),
                ('invoice_copy_text', models.CharField(default='Original (खरिदकर्ताको प्रति)', max_length=50)),
                ('declaration_text', models.TextField(default='We certify that this invoice reflects the actual price of goods/services described.')),
                ('terms_and_conditions', models.TextField(default='1. Goods once sold are not returnable.\n2. Payment is due within 30 days.')),
                ('footer_signature_label', models.CharField(default='Authorized Signatory / अधिकृत हस्ताक्षर', max_length=100)),
            ],
        ),
    ]
