# Generated by Django 6.1.1 on 2026-09-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_invoice_cancellation_reason_invoice_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_vat_exempt',
            field=models.BooleanField(default=False, verbose_name='VAT Exempt Entity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='free_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total value of 100% free goods', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gross_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of gross line amounts', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='percent_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='percent_discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxable_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='value_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hs_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Designates 100% free goods'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='promo_badge',
            field=models.CharField(blank=True, help_text="e.g. 'Pilot Pen Free Promo'", max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='PAN / VAT ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(help_text='Full product title, e.g. Asian Paints Apex Ultima', max_length=200)),
                ('hs_code', models.CharField(blank=True, max_length=50, verbose_name='HS Code')),
                ('unit', models.CharField(default='Pcs', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounting.company')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='accounting.product'),
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., VAT 13%, Excise Duty 5%, TDS 1.5%', max_length=100)),
                ('tax_type', models.CharField(choices=[('VAT', 'Value Added Tax (VAT)'), ('EXCISE', 'Excise Duty'), ('TDS', 'Tax Deducted at Source (TDS)'), ('OTHER', 'Other Indirect Tax')], default='VAT', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage rate (e.g., 13.00)', max_digits=5)),
                ('fiscal_year', models.CharField(default='2083/084', help_text='Applicable Nepalese Fiscal Year', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='accounting.company')),
                ('ledger_account', models.ForeignKey(blank=True, help_text='Associated Liability or Asset Ledger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_configs', to='accounting.account')),
            ],
            options={
                'unique_together': {('company', 'name', 'fiscal_year')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='products', to='accounting.taxconfiguration'),
        ),
        migrations.AddField(
            model_name='customer',
            name='applicable_taxes',
            field=models.ManyToManyField(blank=True, related_name='customers', to='accounting.taxconfiguration'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'name')},
        ),
    ]
