# Generated by Django 6.1.1 on 2026-09-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_ird_creditnote_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Standard Nepal IRD Schedule 6 Credit Note', max_length=100)),
                ('page_size', models.CharField(choices=[('A4_PORTRAIT', 'A4 Portrait (210mm x 297mm)'), ('A4_LANDSCAPE', 'A4 Landscape (297mm x 210mm)'), ('A5_PORTRAIT', 'A5 Portrait (148mm x 210mm)'), ('A5_LANDSCAPE', 'A5 Landscape (210mm x 148mm)')], default='A4_PORTRAIT', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('show_hs_code', models.BooleanField(default=True)),
                ('header_subtitle', models.CharField(default='अनुसूची–६ (नियम १७ सँग सम्बन्धित) / Schedule 6 (Rule 17), VAT Rules 2053', max_length=150)),
                ('declaration_text', models.TextField(default='We certify that this credit note reflects the actual return or price adjustment of goods/services described.')),
                ('terms_and_conditions', models.TextField(blank=True, default='1. Credit adjustment subject to reconciliation.\n2. Applicable against subsequent invoices.')),
                ('footer_signature_label', models.CharField(default='Authorized Signatory / अधिकृत हस्ताक्षर', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_templates', to='accounting.company')),
            ],
        ),
    ]
