# Generated by Django 6.1.1 on 2026-09-25 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_creditnotetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_percent_discount', models.BooleanField(default=True, verbose_name='Enable % Discount')),
                ('enable_value_discount', models.BooleanField(default=True, verbose_name='Enable Value Discount')),
                ('enable_free_item_discount', models.BooleanField(default=True, verbose_name='Enable Free Item (100% Free) Option')),
                ('enable_promotions', models.BooleanField(default=True, verbose_name='Enable Promotional Badges')),
                ('allow_quick_customer_creation', models.BooleanField(default=True, verbose_name='Allow creating Customers directly during Invoicing')),
                ('allow_quick_product_creation', models.BooleanField(default=True, verbose_name='Allow creating Products directly during Invoicing')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounting.company')),
            ],
        ),
    ]
