# Generated by Django 6.1.1 on 2026-09-25 07:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_customer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnoteitem',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='hs_code',
            field=models.CharField(blank=True, default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.product'),
        ),
        migrations.AlterField(
            model_name='creditnoteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='hs_code',
            field=models.CharField(blank=True, default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.product'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='promo_badge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12),
        ),
    ]
