# Generated by Django 6.1.1 on 2026-09-27 09:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_creditnoteitem_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='customer',
            name='ledger_account',
            field=models.ForeignKey(blank=True, help_text='Accounts Receivable (Sundry Debtors)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledgers', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Standard/Default Cost Rate', max_digits=14),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='free_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gross_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='OtherChargeMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_charges', to='accounting.company')),
                ('default_account', models.ForeignKey(blank=True, help_text='Associated COA expense/clearing account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_masters', to='accounting.account')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('supplier_invoice_no', models.CharField(max_length=100)),
                ('supplier_invoice_date', models.DateField()),
                ('nepali_date', models.CharField(blank=True, max_length=10)),
                ('customs_declaration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customs_date', models.DateField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('non_taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('excise_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_inventory_landed_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='accounting.company')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice', to='accounting.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_taxable', models.BooleanField(default=True)),
                ('excise_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('excise_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allocated_other_charge', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('landing_cost_total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16)),
                ('landing_cost_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='accounting.product')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.purchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceOtherCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('charge_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.otherchargemaster')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_charges', to='accounting.purchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pan_vat_number', models.CharField(db_index=True, max_length=9)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounting.company')),
                ('ledger_account', models.ForeignKey(blank=True, help_text='Associated Accounts Payable (Sundry Creditors) account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_ledgers', to='accounting.account')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'pan_vat_number')},
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='accounting.supplier'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounting.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='accounting.warehouse'),
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField(db_index=True)),
                ('entry_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase Invoice'), ('PURCHASE_RETURN', 'Debit Note'), ('SALES', 'Sales Invoice'), ('SALES_RETURN', 'Credit Note'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=20)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reference_number', models.CharField(max_length=100)),
                ('in_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('out_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('balance_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('balance_value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='accounting.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='accounting.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='accounting.warehouse')),
            ],
            options={
                'ordering': ['entry_date', 'created_at'],
                'indexes': [models.Index(fields=['company', 'product', 'warehouse', 'entry_date'], name='accounting__company_c0b7f5_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoice',
            unique_together={('company', 'invoice_number')},
        ),
    ]
