# Generated by Django 6.1.1 on 2026-09-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_account_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='applicable_taxes',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='accounting.taxconfiguration'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_vat_exempt',
            field=models.BooleanField(default=False, verbose_name='VAT Exempt Entity'),
        ),
    ]
