# Generated by Django 6.1.1 on 2026-09-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_supplier_applicable_taxes_supplier_is_vat_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_invoice_date_bs',
            field=models.CharField(blank=True, help_text='Format: YYYY-MM-DD', max_length=10, verbose_name='Supplier Bill Date (BS)'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_invoice_date',
            field=models.DateField(db_index=True),
        ),
    ]
