# Generated by Django 6.1.1 on 2026-09-29 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_purchaseinvoice_supplier_invoice_date_bs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='credit_note_date_bs',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date_bs',
            field=models.CharField(blank=True, help_text='Format: YYYY-MM-DD', max_length=10, verbose_name='Invoice Date (BS)'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
