# Generated by Django 6.1.1 on 2026-09-30 05:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_creditnote_credit_note_date_bs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_note_number', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('debit_note_date_bs', models.CharField(blank=True, help_text='Format: YYYY-MM-DD', max_length=10)),
                ('reason', models.CharField(choices=[('GOODS_RETURN', 'Goods Returned to Supplier'), ('DAMAGED_EXPIRED', 'Damaged, Defective or Expired Goods'), ('RATE_DIFFERENCE', 'Price / Rate Overcharge Correction'), ('DISCOUNT_POST_PURCHASE', 'Post-Purchase Rebate / Discount'), ('OTHER', 'Other Regulatory Adjustment')], default='GOODS_RETURN', max_length=50)),
                ('reason_details', models.TextField(blank=True)),
                ('taxable_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('excise_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_inventory_cost_reversed', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16)),
                ('print_count', models.PositiveIntegerField(default=0, verbose_name='Times Printed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='accounting.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_debit_notes', to=settings.AUTH_USER_MODEL)),
                ('original_purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='accounting.purchaseinvoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='accounting.supplier')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_note', to='accounting.transaction')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('company', 'debit_note_number')},
            },
        ),
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('hs_code', models.CharField(blank=True, default='-', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('original_unit_landed_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('excise_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.debitnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_items', to='accounting.product')),
            ],
        ),
        migrations.CreateModel(
            name='DebitNoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Standard Nepal IRD Schedule 8 Debit Note', max_length=100)),
                ('page_size', models.CharField(choices=[('A4_PORTRAIT', 'A4 Portrait (210mm x 297mm)'), ('A4_LANDSCAPE', 'A4 Landscape (297mm x 210mm)'), ('A5_PORTRAIT', 'A5 Portrait (148mm x 210mm)'), ('A5_LANDSCAPE', 'A5 Landscape (210mm x 148mm)')], default='A4_PORTRAIT', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('show_hs_code', models.BooleanField(default=True)),
                ('header_subtitle', models.CharField(default='अनुसूची–८ (नियम १७ सँग सम्बन्धित) / Schedule 8 (Rule 17), VAT Rules 2053', max_length=150)),
                ('declaration_text', models.TextField(default='We certify that this debit note reflects the actual return or price adjustment of goods/services described.')),
                ('terms_and_conditions', models.TextField(blank=True, default='1. Debit adjustment subject to vendor ledger reconciliation.\n2. Applicable against outstanding payable bills.')),
                ('footer_signature_label', models.CharField(default='Authorized Signatory / अधिकृत हस्ताक्षर', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_templates', to='accounting.company')),
            ],
        ),
    ]
