# Generated by Django 6.1.1 on 2026-10-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_debitnote_debitnoteitem_debitnotetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2083/084', max_length=20)),
                ('code', models.CharField(help_text='e.g., 8384', max_length=10)),
                ('start_date_bs', models.CharField(help_text='YYYY-MM-DD (e.g. 2083-04-01)', max_length=10)),
                ('end_date_bs', models.CharField(help_text='YYYY-MM-DD (e.g. 2084-03-31)', max_length=10)),
                ('start_date_ad', models.DateField()),
                ('end_date_ad', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='accounting.company')),
            ],
            options={
                'ordering': ['-start_date_ad'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INV', 'Sales Invoice (कर बीजक)'), ('PINV', 'Purchase Inwards (खरिद बीजक)'), ('CN', 'Credit Note (क्रेडिट नोट)'), ('DN', 'Debit Note (डेबिट नोट)'), ('JV', 'Journal Voucher')], max_length=10)),
                ('prefix', models.CharField(default='INV', help_text='e.g., INV, PINV, CN, DN', max_length=10)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('padding_digits', models.PositiveIntegerField(default=6, help_text='Zero padding (6 digits produces 000001)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='accounting.company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='accounting.fiscalyear')),
            ],
            options={
                'unique_together': {('company', 'fiscal_year', 'document_type')},
            },
        ),
    ]
